run:
  timeout: 5m
  output:
    format: tab

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental

linters:
  enable:
    - bodyclose
    - megacheck
    - revive
    - govet
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - stylecheck
    - gochecknoinits
    - exportloopref
    - gocritic
    - nakedret
    - gosimple
    - prealloc
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
  exclude-use-default: false